- magik-session.el
Use the 'magik-utils-delete-process-safely' instead of the redundant 'sw-delete-process-safely'.
This function is used to delete Magik sessions when there is no Magik prompt available, eg. midway through startup.
> Use correct version of delete-process-safely

- magik-cb.el
Change the internal names in magik-cb to reflect the current naming scheme.
After this change the CB menu works, and it is also now possible to view and edit CB customisation options.
> CB menu options working - CB customisation options working

- magik-mode.el
Corrected the name of the callback function of the pull down menu entry Magik -> Toggle... -> #Debug Statements
> magik-mode: Pulldown-Menu Toggle #DEBUG Statements didn't work

- magik-mode.el
> magik transmit anything didn't work under Linux due to Windows-like 

- magik-version.el
* prior to that change last directory element has been omitted when adding a new gis version, which was quite irritating to the user
* under GNU/Linux: in GIS-Version directory no longer '/' is replaced by '\'
> improve magik-version-read-smallworld-gis

- README.md
* Hint usage of outline-minor-mode with magik-files
* Hint for usage of imenu with magik-Files
* Hints for usage with Smallworld 4.x (Although with Smallworld 4.x an EMACS has been delivered, which works well, there might be several reasons to use the MELPA package not only for Smallworld 5.x but also for older Smallworld versions. I've added a few things worth to be mentioned).
> Added some hints to README.md

- README.md
- magik-cb.el
- magik-keys.el
- magik-menu.el
- magik-mode.el
- magik-module.el
- magik-product.el
- magik-session.el
With this Pull-Request several problems are fixed:
* correct missspelled callback functions of menu entries and key bindings
* removed non-functioning hints for short cuts in menu entries. 
* activated f4-key-combinations from former 'CST 430 emacs' in magik-mode
* comment out menu entries and key bindings, where no callback function is available. This gives the possibility for maintainers to add them later on, without the user beeing annoyed by a non functioning menu entry
* replace 'space' by 'SPC' as shortcut-hint in pulldown menus, which is the usually used naming for that key
* renaming a few functions for clarity as the menu names have been changed with respect to the former 'CST 430 emacs' and update their public comments:
`magik-session-update-magik-session-menu` (has been …
> Fix broken menu entries etc

- magik-indent.el
- magik-mode.el
Besides strings with double quote delimiters like `"What's going on?"` Magik also allows strings to be delimited by single quotes like `'Tom said: "It is quite easy", but it is not.'`. With this pull request the magik-mode supports this, too.
> Support for Strings with single quote delimiters

- magik-cb.el
The mf files for the method finder, which are delivered by GE for many entries contain the $SMALLWORLD_GIS variable as part of the path to the magik file. Although the sources of these magik files normally are not delivered, there is no reason to not expand this variable under GNU/Linux as well (like it works under Windows). So the change restores the functionality of the former EMACS delivered with the SW 4.x installation.
> mf Variable substitution didn't work under GNU/Linux

- magik-indent.el
- magik-mode.el
Reverts roadrunner1776/magik#22
Causes display problems with various strings, for example:
Magik> write("Doesn't understand")
Also, some display issues within the method finder/class browser
> Revert "Support for Strings with single quote delimiters"

- magik-electric.el
When you have the same filename opened from 2 different directories, the filename_as_symbol would become person.magik<directory_name>.
Example:
- person.magik in the directory develop
- person.magik in the directory master
Inserting def_slotted_exemplar for person.magik in develop would become:
`def_slotted_exemplar(:person.magik<develop>,`
Background info:
The `buffer-name` function returns the name of the buffer, not the name of the file which backs it; therefore it's not the true file name, since it can be filename<2> in the case of an indirect buffer, or *scratch*, which has no backing file at all. The function you want is `buffer-file-name`, which returns the full path (or nil);
> [magik-electric] Buffer name as filename isnt always safe

- magik-mode.el
By adding this, we support adding sw-method-docs for assignment methods:
```
_method person.name << a_name
_self.name << a_name
_endmethod
$
```
> [sw-method-docs] Add support for assignment method

- magik-mode.el
Remove old F2-m references -> replaced by magik-single-sw-method-docs
> [magik-mode] Remove old F2-m references

- magik-loadlist.el
[magik-loadlist] Get rid om temp-buffer when updating loadlist using `C-c r`
> [magik-loadlist] Get rid om temp-buffer when updating loadlist using `C-c r`

- magik-session-extras.el
It took a long while :)
But this pull request adds the ability to jump to method definition/source from a traceback or output lines from .apropos() directly from the prompt.
It will also highlight the corresponding lines.
Example:
It uses the magik-cb-process in the background, so to use it you need to at least open the class browser once.
I am not an expert at elisp, therefore if there is any feedback it is appreciated. :)
The reason why we inline magik code instead of only via elisp, is because for the magik-cb-send-string we need the package name and the exemplar. However the traceback lines (or from apropos) don't provide the package name, only the exemplar name. Therefore we use the method_finder in magik to find the package and via the magik-session-filter do a callback to …
> Magik session extras

- magik-mode.el
The key binding `<f2> m` for 'magik-single-sw-method-docs' hides the same key binding for 'magik-transmit-method' which is defined within magik-keys.el
As the 'magik-transmit-method' many people use very frequently using exactly this key binding, it seems to me to be important to avoid this conflict, although there might be are other workarounds.
With this pull request I change the key bindings for four functions in an easy to remember logical way:
* `<f2> d` 'magik-single-sw-method-docs'
* `<f2> D` 'magik-file-sw-method-docs'
* `<f2> p` 'magik-single-pragma' (unchanged)
* `<f2> P` 'magik-file-pragma' 
So now the 'single'-functions have a lowercase latter, whereas the 'file' functions have the corresponding uppercase latter.
d/D stands for method-**d**ocs
p/P stands for **p**ragma
> avoid key binding conflict f2 m

- magik-session.el
A colleague of mine, who startet using magik but has had long experience with EMACS, was irritated that a prefix argument (e.g. given by C-u) has no influence for the <kbd>Ctrl</kbd><kbd>k</kbd> (`magik-session-kill-line`) command within the magik-session-mode. In fact it is a bit strange, that of all these `magik-session-(do any simple edit)` functions this is the only one, which doesn't pass the `arg` do the simple edit function (The same holds for the previously with SW 4.x or earlier delivered EMACS versions).
So one can think about the reason. 
There might be a connection to the question the user sees when calling `magik-session-kill-region`
> Cutting and pasting big regions can confuse the gis-mode markers. Kill anyway?
On the other hand, I never had seen great problems with that, …
> magik-session-kill-line no longer ignores arg

- .gitignore
- magik-aliases.el
- magik-cb.el
- magik-mode.el
- magik-msg.el
- magik-session.el
- magik-treesit.el
- magik-utils.el
Work in progress. Only tested on Emacs 29+ ; probably needs some work to get the original magik-mode working again on Emacsen without tree-sitter support (Emacs 28 and older).
> Inititial tree-sitter-magik support

- magik-mode.el
This function adds a space to keywords, but if the current word is longer than the keyword itself, it added a `_` as well which was highly unwanted. The wanted behaviour is written down here:
`self` + <SPACE> --> `_self`
`self_explaining` + <SPACE> --> `self_explaining`
> [magik-mode] Use a regexp to match the abbrev words

- magik-mode.el
- magik-treesit.el
Depends on the next version of [tree-sitter-magik](https://github.com/krn-robin/tree-sitter-magik).
This will font-lock all parameters inside the `[` and `]` correctly. The upper buffer is the `magik-mode` and the lower buffer is the `magik-ts-mode`.
> [magik-treesit] Add font-lock-rule for indexing method and use more magik-faces

- magik-mode.el
`magik-font-lock-keywords-1` is used in `magik-session`. By moving `false`, `true` and `maybe` from `magik-keyword-constants` to it's own group `magik-keyword-kleenean`, we need to add this new group to the same constructions as `magik-keyword-constants`.
> [magik-mode.el] Add kleenean to `magik-font-lock-keywords-1`

- magik-treesit.el
- Use `0` for all operators to indent the next snippet to:
```
_block
a _and
b
_endblock
$
```
instead of:
```
_block
a _and
b
_endblock
$
```
- Fix indent rule for `_finally` to indent the next snippet to:
```
_loop
<do_something>
_finally
<do_something>
_endloop
```
instead of:
```
_loop
<do_something>
_finally
<do_something>
_endloop
```
> magik-treesit: update indent rules

- magik-aliases.el
- magik-cb.el
- magik-loadlist.el
- magik-module.el
- magik-msg.el
- magik-pragma.el
- magik-product.el
- magik-session.el
- magik-version.el
Added mode-maps to the docstrings. 
This way the keybindings of the maps are easily discoverable through `describe-mode` (C-h m).
> Mode-maps added to the doc strings of the mode functions.

- magik-lint.el
Release: https://github.com/StevenLooman/magik-tools/releases/tag/0.9.1
Change log: https://github.com/StevenLooman/magik-tools/blob/f46c7870ddb8c5c7eaed03e2d8684c8bdbdde4ed/CHANGES.md?plain=1#L11
CC: @StevenLooman
> Bump the magik linter to 0.9.1

- magik-utils.el
Prompt by default for magik-utils-get-buffer-mode when magik-utils-by-default-prompt-buffer-p is set.
This allows for a workflow to prompt by default for gis or class-browser buffers when they are not visible or there are multiple sessions running.
Without the need for a prefix-argument.
Also when multiple gis sessions are running, or multiple gis sessions/buffers have been made over the course of the emacs session. Then the DEFAULT value is wrong most of the time. And because of that the interactive command which uses magik-utils-get-buffer-mode fails.
This new functionality is put behind a customization option so that users can choose which behaviour they want. And to not interrupt people's current workflow.
> Prompt for gis buffers when customization is set

- magik-electric.el
The current template creates invalid code:
```
Magik> _proc 
sw:write("Hello Smallworld")
_endproc.invoke()
**** Error (parser_error): on line 2
sw:write("Hello Smallworld")
^
Expected '('
```
The new template fixes this:
```
Magik> _proc()
sw:write("Hello Smallworld")
_endproc.invoke()
Hello Smallworld
```
> [magik-electric] Add brackets to `proc` template

- magik-electric.el
The current template creates invalid code after using an exemplar name earlier in the file:
```
_pragma(classify_level=, topic={}, usage={})
shape_mixin.def_mixin(:,
)
$
```
The new template fixes this:
```
_pragma(classify_level=, topic={}, usage={})
def_mixin(:shape_mixin,
{}
)
$
```
> [magik-electric] Move `def_mixin`, use `filename_as_symbol` and add empty vector for parents

- .github/workflows/test.yml
MacOS-11 image is dropped since June; another solution is to use MacOS-12, but that is a short-term solution as that image will be deleted over time as well.
https://github.com/purcell/nix-emacs-ci/pull/268
https://github.com/purcell/setup-emacs/issues/48
> CI: drop MacOS-11, bump Emacs 29.x to 29.4

- magik-treesit.el
Fix indent rule for _finally to indent the next snippet to:
```
_loop
<do_something>
_finally
<do_something>
_endloop
```
instead of:
```
_loop
<do_something>
_finally
<do_something>
_endloop
```
> [magik-treesit] Add correct indent rule for `_finally`

- magik-session.el
Also show an error if there is no active process running in the buffer when trying to scroll through the commands history.
> [magik-session] Fix command history in sequential Magik sessions

- magik-doc-gen.el
Due to a typo, the require statement could not be found.
> type and sw docs dependency corrected

- magik-session.el
Also changed to `string-equal`
> [magik-session] Use built-in Emacs functionality to determine shell

- magik-aliases.el
In #162  a bracket was moved with the removal of a whitespace
> Move bracket that blocks alias selection

- magik-mode.el
The keybindings 
- <f2> - up
- <f2> - down
- M - up
- M - down
gave errors when at the end or start of file like such:
This makes small wrappers, that set the no error parameter to true
> added safe method

- magik-cb.el
`bufs` and `visible-bufs` need to be fully assigned before `buffer` is evaluated.
CC: @reinierkof
> [magik-cb] Don't set in one go

- magik-aliases.el
When restarting a session, the time is shown as well, so why not when starting it the first time?
> [magik-aliases] Insert current time when starting

- magik-aliases.el
- magik-cb.el
- magik-mode.el
- magik-session.el
- magik-template.el
- magik-version.el
Stop using `SMALLWORLD_GIS`, but send/retrieve the value if needed without changing the running sessions.
Also fix selecting a definition from the easy-menu.
> [magik-version] Stop setting `SMALLWORLD_GIS`

- snippets/magik-mode/.yas-setup.el
Because of the reverse in the loop itself, it only returned the first slot
CC: @reinierkof
> [yasnippet] Reverse the list before the loop

- magik-mode.el
- magik-module.el
- magik-product.el
- magik-trn.el
For trn mode:
- just use the basic yas-magik-expand
for product and module mode,
check whether the leading character has a keyword or a name-face font. 
if it does we allow completion with <space>
I checked that all snippets work as intended.
When writing e.g. a description nothing is being completed, which is desired
> Simplify completions in module, product and trn mode.

- magik-session.el
Starting a new session (using F2-z) only worked if you had the previous session buffer active.
If you did not have the previous buffer active or if you killed the buffer completely, it could not start.
Added `t` as predicate for `magik-utils-get-buffer-mode`, because otherwise the predicate would be to only take buffers into account that had an active process.
Added `(generate-new-buffer-name (or magik-session-buffer magik-session-buffer-default-name))` in case of the previous Magik Session buffer was killed completely, but F2-z still knew the command. This would then create a new buffer with the old command.
> Fix for restarting a session after the previous one was killed

- magik-mode.el
Fix magik-regexp not known in magik-mode (after e32caf604cbffc6addae11ab533a40f3175b626b)
> [magik-mode] fix for magik-regexp

- magik-session-extras.el
For when printing a large number of methods or for a traceback, the font locking could take a long time. So I tried to fix this by tweaking the regex that is used for the font-locks
> Optimize the faces for magik-session-extras

- magik-version.el
> Restore minimal support for SW_GIS env variable set outside Emacs

- magik-lint.el
Issue:
It only marked the start of the issue and not the complete range.
This PR also fixes the empty ID column:
> [magik-lint] Correctly parse `end_line/end_column` and `symbol`
