magik-cb.el
A small feature that a colleague and I found useful, but missing currently from magik-mode, is to jump back more easily to the definition of a method we already searched for in the class browser.  Instead of looking it up in the class browser again.
Currently we implemented it with a variable (list) that holds the history of the methods you jumped to via the class browser and its current position in that history list. A method gets added to this list when you jump via the class browser to the method definition.
Then with the functions  magik-cb-jump-previous and magik-cb-jump-next, you are able to jump to previous or next method definition in the history list (relative to your current position).
Or use  magik-cb-jump-select (magik-cb-ido-jump-select) to select the method directly from a …
=> cb jump history feature

magik-lint.el
Upgrade to magik-lint-0.5.1.jar
=> Upgrade to latest magik-lint

magik-mode.el, magik-treesit.el
A couple of minor fixes that were broken after the initial tree sitter implementation
=> Font-lock fixes

magik-aliases.el, magik-electric.el, magik-indent.el, magik-mode.el, magik-session-filter.el, magik-treesit.el
Add magik tree sitter indenting
=> Add magik-ts-mode indenting

magik-mode.el, magik-treesit.el
No more dependency on 'treesit-auto'
=> Better initialisation of magik-ts-mode

magik-lint.el
Give a one-time warning if `magik-lint*.jar`  could not be found; instead of giving an error each time a `magik`  file is being opened.
=> Warn when magik-lint jar is not found

magik-aliases.el, magik-cb.el, magik-module.el, magik-session.el, magik-version.el
Fixes for abcf2c75c9843aa815ec77572b45d14a2069d572
=> Fixes after converting to `define-derived-mode`

snippets/magik-mode/.yas-setup.el
=> Refactor the .yas-setup (and extend prev-class-name)

snippets/magik-mode/.yas-setup.el
=> [magik-yasnippet] Refactor `magik-yasnippet-module-name`

magik-mode.el
=> [magik-mode] Use built-in Emacs functionality to create temporary file

magik-session.el
Also give a `user-error` if there is no match
=> [magik-session] Don't move the line when no match is found

magik-session.el
=> [magik-session] Use `before-change-functions` to replace some keys

magik-aliases.el, magik-cb.el, magik-lint.el, magik-loadlist.el, magik-mode.el, magik-module.el, magik-msg.el, magik-product.el, magik-session-extras.el, magik-session.el, magik-version.el
Also:
- introduce some mode-specific `deffgroup`
- fix some font-locking issues
- add extra font-locking for module.def/product.def
=> Update all faces to use Magik-own faces

magik-ts-mode.el
=> [magik-ts-mode] Improve indentation for invoke

magik-ts-mode.el
=> [magik-ts-mode] Improve indentation for defvar's

magik-electric.el
=> [fix] Prevent void symbol in package quickstart

magik-electric.el
=> Lazy load magik-electric

magik-version.el
=> [magik-version] Font-lock invalid quoted directories as well

magik-aliases.el, magik-session.el, magik-utils.el
Fixes #10
This also enables users to start a session with just `F2-z` on startup, if setup correctly, while highly discouraged.
=> Replace `%...%` with `${...}`

magik-version.el
=> [magik-version] Call the `read-only-mode` to trigger any hooks
